# Ejercicios - Clase 4

Ejercicios de los bloques de introducción a python. Bucles y condicionales

**Versión**: 1.0

**Fecha**: 13/10/2023

## Ejercicio 1

Vamos a comprobar si un número `n` es primo o no.

In [23]:
n = 8

# TO-DO comprueba si un número es primo o no rellenando la variable es_primo
es_primo = True
for d in range(2, n//2):
    if n%d == 0:
        es_primo = False

if es_primo:
    print(" El número {} es primo".format(n))
else:
    print(" El número {} no es primo".format(n))

 El número 8 no es primo


Posibles respuestas:

- El número 21 no es primo
- El número 5 es primo
- El número 2 es primo
- El número 8 no es primo

## Ejercicio 2

Vamos a calcular la `media` y la `desviación estándar` de un conjunto de números. Los números van a ser generados con una media y una desviación estándar conocidos, por lo que tiene que dar el mismo valor. Recordad las ecuaciones de la media y std:

$$\mu = \frac{\sum_i^Nx_i}{N}$$

$$\sigma = \sqrt{\frac{\sum_i^N(x_i - \mu)^2}{N}}$$

In [17]:
import random
import math

# Puedes cambiar estos valores para generar nuevas distribuciones
media_teorica = 4.0
desviacion_teorica = 2.0
N = 10000

# ¿Cómo funciona esta línea para generar números aleatorios con distribución normal?
datos = [random.gauss(media_teorica, desviacion_teorica) for _ in range(N)]

# TO-DO calcula la media y la std
media = sum(datos) / N
numerador = [(datos[i] - media)**2 for i in range(N)]
std = math.sqrt(sum(numerador)/N)

print("Media esperada: {:.2f}\t\tStd esperada: {:.2f}".format(media_teorica, desviacion_teorica))
print("Media real: {:.2f}\t\tStd real: {:.2f}".format(media, std))

Media esperada: 4.00		Std esperada: 2.00
Media real: 4.01		Std real: 2.00


## Ejercicio 3

Vamos a crear el juego de la ruleta en un casino. Vamos a utilizar un diccionario para guardar las `apuestas`, donde la clave será el número al que apostamos y el valor será el dinero que apostamos. Además, permitiremos apostar todas las veces que queramos hasta que digamos que no. En el caso en que apostemos dos veces al mismo número, las apuestas deben sumarse.

Una vez se hayan definido las apuestas, se mostrará por pantalla el listado de apuestas y el total apostado. Después se lanzará la bola de la ruleta y comprobaremos qué ha pasado. Recuerda que si has acertado, ganas 36 veces lo apostado por el número.



In [28]:
import random

# TO-DO Define tus variables para guardar las apuestas
apuestas = {}

# TO-DO Construye el bucle para seguir apostando
seguir_apostando = True
while seguir_apostando:
    # TO-DO pide el valor de la apuesta
    apuesta = float(input("Introduce el valor de tu apuesta: "))
    
    # TO-DO pide el valor del número al que apuestas
    numero = int(input("Introduce el número al que apuestas {:.2f}: ".format(apuesta)))
    
    # TO-DO comprueba si ya has apostado a ese número antes y gestiónalo según el enunciado
    if numero not in apuestas:
        apuestas[numero] = apuesta
    else:
        apuestas[numero] += apuesta
        
    print("Apuesta registrada. {:.2f} al número {}".format(apuesta, numero))
    
    # TO-DO pide la condición de salida para seguir apostando o no
    respuesta = input("¿Quieres seguir apostando? (S/N): ")
    if respuesta != "S":
        seguir_apostando = False
        print("\nNo va más")
     
print("\nListado de apuestas:")
print(apuestas)

# TO-DO calcula el total que se ha apostado
total = sum([apuestas[n] for n in apuestas])
print("Has apostado un total de {:.2f}".format(total))

print("\nLa ruleta empieza a girar...")

# TO-DO calcula el valor de la ruleta
ruleta = random.randint(0, 36)
print("Ha salido el número {}.".format(ruleta))

# TO-DO gestiona si has acertado o no
if ruleta in apuestas:
    retorno = apuestas[ruleta] * 36
    print("ACIERTO! Has ganado {:.2f}. Por tanto, has recuperado {:.2f}".format(retorno, retorno - total))
else:
    print("FALLO! Has perdido {:.2f}".format(total))

print("Gracias por jugar. Hasta la próxima.")

Introduce el valor de tu apuesta: 10
Introduce el número al que apuestas 10.00: 8
Apuesta registrada. 10.00 al número 8
¿Quieres seguir apostando? (S/N): S
Introduce el valor de tu apuesta: 5
Introduce el número al que apuestas 5.00: 4
Apuesta registrada. 5.00 al número 4
¿Quieres seguir apostando? (S/N): S
Introduce el valor de tu apuesta: 5
Introduce el número al que apuestas 5.00: 22
Apuesta registrada. 5.00 al número 22
¿Quieres seguir apostando? (S/N): S
Introduce el valor de tu apuesta: 5
Introduce el número al que apuestas 5.00: 8
Apuesta registrada. 5.00 al número 8
¿Quieres seguir apostando? (S/N): N

No va más

Listado de apuestas:
{8: 15.0, 4: 5.0, 22: 5.0}
Has apostado un total de 25.00

La ruleta empieza a girar...
Ha salido el número 6.
ACIERTO! Has ganado 540.00. Por tanto, has recuperado 515.00
Gracias por jugar. Hasta la próxima.


**Ejemplo de partida**

```
Introduce el valor de tu apuesta: 10
Introduce el número al que apuestas 10.00: 8
Apuesta registrada. 10.00 al número 8
¿Quieres seguir apostando? (S/N): S
Introduce el valor de tu apuesta: 5
Introduce el número al que apuestas 5.00: 4
Apuesta registrada. 5.00 al número 4
¿Quieres seguir apostando? (S/N): S
Introduce el valor de tu apuesta: 5
Introduce el número al que apuestas 5.00: 22
Apuesta registrada. 5.00 al número 22
¿Quieres seguir apostando? (S/N): S
Introduce el valor de tu apuesta: 5
Introduce el número al que apuestas 5.00: 8
Apuesta registrada. 5.00 al número 8
¿Quieres seguir apostando? (S/N): N

No va más

Listado de apuestas:
{8: 15.0, 4: 5.0, 22: 5.0}
Has apostado un total de 25.00

La ruleta empieza a girar...
Ha salido el número 8.
ACIERTO! Has ganado 540.00. Por tanto, has recuperado 515.00
Gracias por jugar. Hasta la próxima.
```